apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: loxation-messaging
  namespace: '696735170560'
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/client-name: gcloud
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"  # Single instance for LMDB consistency
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/sessionAffinity: "true"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      serviceAccountName: 696735170560-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/loxation-f8e1c/loxation-messaging:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: RUST_LOG
          value: "debug"
        - name: GOOGLE_CLOUD_PROJECT
          value: "loxation-f8e1c"
        - name: FIREBASE_PROJECT_ID
          value: "loxation-f8e1c"
        - name: ALLOWED_ORIGINS
          value: "*"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"  # Increased from 512Mi for Rust + LMDB
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080